### ISSUE TITLE
what is the call from combined vcf that has no caller info

### ISSUE THREAD

**Issue by arkyl** [dnanexus/parliament2#3] opened 2018-06-19 15:17 UTC
Hi,
I run parliament2 on DNAnexus. I am wondering what the calls are, that has no caller info. E.g:
chr1    819974  DEL00162134SUR  N       <DEL>   .       PASS    SUPP=1;AVGLEN=385;SVTYPE=DEL;SVMETHOD=SURVIVORv2;CHR2=1;END=820359;STRANDS=+-   GT:SP   ./.:.

I suppose that each call is from a caller. so is the above call from a caller but the info of the caller was not provided because it was genotyped? Thanks much !

**Comment by fritzsedlazeck** [comment] 2018-06-19 15:53
Hi,
thanks for reaching out. Can you explain if this is a per sample call or merged over multiple samples. In addition I am wondering if you could post multiple entries or if this is a full line or just cut? 
Thanks
Fritz

**Comment by arkyl** [comment] 2018-06-22 18:11
Sorry, didn't see this.
It's a one sample vcf. My question is more about the output format. I attach a two line example txt. One line has CALLER info: MANTA. The other line didn't have caller info. In that case, can we know the caller that makes the SV call? Thanks much.


[example.txt](https://github.com/dnanexus/parliament2/files/2128666/example.txt)

**Comment by slzarate** [comment] 2018-07-17 17:43
Hi, are you running SVTyper to generate the VCF file?

**Comment by arkyl** [comment] 2018-07-17 19:01
Hi Samantha,
Thanks for the reply. I used the parliament2 pipeline, which I believe used
SVTyper.

I think I can now understand the output better. There is a
*combined.genotyped.vcf
file. In this file, there is SUPP info, e.g:

SUPP=3;,  but there is no info about which 3 callers support the call.

I think the naive SURVIVOR output would have this info.

Thanks.

Yue

**Comment by fritzsedlazeck** [comment] 2018-07-17 19:05
Hi Yue,
There are other flags in the INFO field that show that. Ultimately you can check these in the genotype caller columns subsequent of  column 9 (I think). 

thanks
Fritz

**Comment by fritzsedlazeck** [comment] 2018-07-17 19:32
Mhm yeah, because `CALLERS=MANTA,DELLY` is not a SURVIVOR output. 
Thx
Fritz

**Comment by slzarate** [comment] 2018-07-17 20:11
Hi, this is a known bug with the version of SVTyper in this image. Within the next day or so I will be putting out a new release, and this should resolve your error. Stay tuned.

**Comment by slzarate** [comment] 2018-07-19 16:30
@arkyl Hi, I believe this has been resolved by #12. Please download the 0.1.7 release and see if it works for you.

**Comment by arkyl** [comment] 2018-07-23 13:55
Hi Samantha,
I run the parliament2 0.1.7 on DNAnexus. I think the combined vcf still
didn't have the call info for the ones that were not genotyped, i.e., the
SP field in GT:SP is probably from SVtyper, not from SURVIVOR. When the
call was not genotyped, the support SV caller info was lost. Thanks.

e.g:
#when a call was not genotyped

chr1    921340  INV0076397SUR   N       <INV>   .       PASS
SUPP=1;AVGLEN=103;SVTYPE=INV;SVMETHOD=SURVIVORv2;CHR2=1;END=921443;STRANDS=++
  GT:SP   ./.:.
#when SUPP=3; but there is only one caller info

chr1    1350001 DEL0075681SUR   N       <DEL>   .       PASS
SUPP=3;AVGLEN=1365;SVTYPE=DEL;SVMETHOD=SURVIVORv2;CHR2=1;END=1351400;STRANDS=+-;CALLERS=CNVNATOR
      GT:SP   1/1:CNVNATOR


Yue

**Comment by slzarate** [comment] 2018-08-22 00:35
Hi Yue,

OK, so I have looked into this and this is a feature, not a bug. What this means is that a caller has found something, but it hasn't been orthogonally verified, so use that call at your own risk. As a result, we will not be resolving this, but thanks for bringing it to my attention!

Samantha

**Closed** 2018-08-22 00:35 UTC
Labels: wontfix
